---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: npm
    directory: "/dp"
    schedule:
      interval: "daily"
      time: "07:00"
 - package-ecosystem: pip
  directory: "/dp"
  schedule:
    interval: "daily"
    time: "07:00"      
